const Countries: string[] = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Germany",
  "France",
  "Spain",
  "Italy",
  "Brazil",
  "Mexico",
  "India",
  "China",
  "Japan",
  "South Korea",
  "Russia",
  "South Africa",
  "Nigeria",
  "Egypt",
  "Turkey",
  "Argentina",
  "Colombia",
  "Chile",
  "Peru",
  "Venezuela",
  "Saudi Arabia",
  "United Arab Emirates",
  "Israel",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Portugal",
  "Greece",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Bulgaria",
  "Croatia",
  "Slovakia",
  "Slovenia",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Ukraine",
  "Belarus",
  "Kazakhstan",
  "Uzbekistan",
  "Vietnam",
  "Thailand",
  "Malaysia",
  "Singapore",
  "Indonesia",
  "Philippines",
  "New Zealand",
  "Ireland",
  "Scotland",
  "Wales",
  "Northern Ireland",
  "Iceland",
  "Luxembourg",
  "Monaco",
  "Liechtenstein",
  "Malta",
  "Cyprus",
  "Georgia",
  "Armenia",
  "Azerbaijan",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Jordan",
  "Lebanon",
  "Syria",
  "Iraq",
  "Iran",
  "Afghanistan",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "Bhutan",
  "Maldives",
  "Mongolia",
  "Myanmar",
  "Cambodia",
  "Laos",
  "Brunei",
  "Timor-Leste",
  "Papua New Guinea",
  "Fiji",
  "Samoa",
  "Tonga",
  "Vanuatu",
  "Solomon Islands",
  "Micronesia",
  "Palau",
  "Marshall Islands",
  "Nauru",
  "Kiribati",
  "Tuvalu",
  "Saint Kitts and Nevis",
  "Antigua and Barbuda",
  "Dominica",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Barbados",
  "Grenada",
  "Trinidad and Tobago",
  "Jamaica",
  "Bahamas",
  "Haiti",
  "Dominican Republic",
  "Cuba",
  "Puerto Rico",
  "Belize",
  "Guatemala",
  "Honduras",
  "El Salvador",
  "Nicaragua",
  "Costa Rica",
  "Panama",
  "Suriname",
  "Guyana",
  "Paraguay",
  "Uruguay",
  "Bolivia",
  "Ecuador",
  "Peru",
  "Chile",
  "Argentina",
  "Brazil",
  "Colombia",
  "Venezuela",
  "Trinidad and Tobago",
  "Barbados",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Grenada",
  "Dominica",
  "Antigua and Barbuda",
  "Saint Kitts and Nevis",
  "Bahamas",
  "Cuba",
  "Haiti",
  "Dominican Republic",
  "Jamaica",
  "Puerto Rico",
  "Belize",
  "Guatemala",
  "Honduras",
  "El Salvador",
  "Nicaragua",
  "Costa Rica",
  "Panama",
  "Mexico",
  "United States",
  "Canada",
  "Greenland",
  "Iceland",
  "Norway",
  "Sweden",
  "Finland",
  "Denmark",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Poland",
  "Germany",
  "Netherlands",
  "Belgium",
  "Luxembourg",
  "France",
  "Switzerland",
  "Austria",
  "Liechtenstein",
  "Monaco",
  "Andorra",
  "Spain",
  "Portugal",
  "Italy",
  "San Marino",
  "Vatican City",
  "Malta",
  "Greece",
  "Cyprus",
  "Bulgaria",
  "Romania",
  "Moldova",
  "Ukraine",
  "Belarus",
  "Russia",
  "Georgia",
  "Armenia",
  "Azerbaijan",
  "Turkey",
  "Syria",
  "Lebanon",
  "Israel",
  "Jordan",
  "Saudi Arabia",
  "Yemen",
  "Oman",
  "United Arab Emirates",
  "Qatar",
  "Bahrain",
  "Kuwait",
  "Iraq",
  "Iran",
  "Afghanistan",
  "Pakistan",
  "India",
  "Sri Lanka",
  "Maldives",
  "Nepal",
  "Bhutan",
  "Bangladesh",
  "Myanmar",
  "Thailand",
  "Laos",
  "Cambodia",
  "Vietnam",
  "Malaysia",
  "Singapore",
  "Brunei",
  "Indonesia",
  "East Timor",
  "Philippines",
  "China",
  "Mongolia",
  "North Korea",
  "South Korea",
  "Japan",
  "Taiwan",
  "Hong Kong",
  "Macau",
  "Australia",
  "New Zealand",
  "Papua New Guinea",
  "Solomon Islands",
  "Vanuatu",
  "Fiji",
  "Samoa",
  "Tonga",
  "Tuvalu",
  "Kiribati",
  "Nauru",
  "Palau",
  "Micronesia",
  "Marshall Islands",
  "New Caledonia",
  "French Polynesia",
  "Wallis and Futuna",
  "American Samoa",
  "Guam",
  "Northern Mariana Islands",
  "Puerto Rico",
  "United States Virgin Islands",
  "British Virgin Islands",
  "Anguilla",
  "Montserrat",
  "Saint Kitts and Nevis",
  "Antigua and Barbuda",
  "Dominica",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Barbados",
  "Grenada",
  "Trinidad and Tobago",
  "Aruba",
  "Curacao",
  "Sint Maarten",
  "Bonaire",
  "Sint Eustatius",
  "Saba",
  "Saint Barthelemy",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Bermuda",
  "Greenland",
  "Iceland",
  "Norway",
  "Sweden",
  "Finland",
  "Denmark",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Poland",
  "Germany",
  "Netherlands",
  "Belgium",
  "Luxembourg",
  "France",
  "Switzerland",
  "Austria",
  "Liechtenstein",
  "Monaco",
  "Andorra",
  "Spain",
  "Portugal",
  "Italy",
  "San Marino",
  "Vatican City",
  "Malta",
  "Greece",
  "Cyprus",
  "Bulgaria",
  "Romania",
  "Moldova",
  "Ukraine",
  "Belarus",
  "Russia",
  "Georgia",
  "Armenia",
  "Azerbaijan",
  "Turkey",
  "Syria",
  "Lebanon",
  "Israel",
  "Jordan",
  "Saudi Arabia",
  "Yemen",
  "Oman",
  "United Arab Emirates",
  "Qatar",
  "Bahrain",
  "Kuwait",
  "Iraq",
  "Iran",
  "Afghanistan",
  "Pakistan",
  "India",
  "Sri Lanka",
  "Maldives",
  "Nepal",
  "Bhutan",
  "Bangladesh",
  "Myanmar",
  "Thailand",
  "Laos",
  "Cambodia",
  "Vietnam",
  "Malaysia",
  "Singapore",
  "Brunei",
  "Indonesia",
  "East Timor",
  "Philippines",
  "China",
  "Mongolia",
  "North Korea",
  "South Korea",
  "Japan",
  "Taiwan",
  "Hong Kong",
  "Macau",
  "Australia",
  "New Zealand",
  "Papua New Guinea",
  "Solomon Islands",
  "Vanuatu",
  "Fiji",
  "Samoa",
  "Tonga",
  "Tuvalu",
  "Kiribati",
  "Nauru",
  "Palau",
  "Micronesia",
  "Marshall Islands",
  "New Caledonia",
  "French Polynesia",
  "Wallis and Futuna",
  "American Samoa",
  "Guam",
  "Northern Mariana Islands",
  "Puerto Rico",
  "United States Virgin Islands",
  "British Virgin Islands",
  "Anguilla",
  "Montserrat",
  "Saint Kitts and Nevis",
  "Antigua and Barbuda",
  "Dominica",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Barbados",
  "Grenada",
  "Trinidad and Tobago",
  "Aruba",
  "Curacao",
  "Sint Maarten",
  "Bonaire",
  "Sint Eustatius",
  "Saba",
  "Saint Barthelemy",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Bermuda",
].sort();

export default Countries;